landing/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
]

local_finances/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landing.urls')),
    path('proveedores/', include('supplies_request.urls')),    
    path('productos/', include('products.urls')),
    path('admin/', admin.site.urls),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
	path('', views.products, name='products'),
	path('<int:id_product>', views.detail, name='product_detail'),
	path('formulario/<int:id_product>/eliminar', views.delete, name='delete_product'),
	path('formulario/<int:id_product>', views.form, name='filled_product_form'),
	path('formulario', views.form, name='product_form'),	
]

supplies_request/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('pedidos', views.supplies_request, name='supplies_request'),
]

landing/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Product(models.Model):
	name = models.CharField('Nombre', max_length=255, unique=True)
	description = models.CharField('Descripción', max_length=500, blank=True, null=True, db_column='descripcion')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		#Some day why the below line dont work
		#return  reverse("products:product_detail", kwargs={"id":self.id}) 

		return f"/productos/formulario/{self.id}"

supplies_request/models.py
from django.db import models
from products.models import Product
# Create your models here.

class SuppliesRequest(models.Model):
	date = models.DateField('Fecha')
	provider = models.CharField('Proveedor', max_length=255)

	def __str__(self):
		return '{} pedido a {} numero de pedido {}'.format(self.date, self.provider, self.id)

class RequestContent(models.Model):
	id_supplies_request = models.ForeignKey(SuppliesRequest, on_delete=models.CASCADE, verbose_name='Pedido')
	id_product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Producto')
	quantity = models.IntegerField('Cantidad')
	cost_d = models.DecimalField('Coste en Dolares',max_digits=15 ,decimal_places=2, default=0)
	cost_b = models.DecimalField('Coste en Bolívares',max_digits=15 ,decimal_places=2, default=0)

	def __str__(self):
		return 'numero de pedido {} pedido el {} a {}: {} cantidad {}'.format(self.id_supplies_request.id ,self.id_supplies_request.date, self.id_supplies_request.provider, self.id_product.name, self.quantity)

landing/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
	return HttpResponse('Hell of Worlds')

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from django.http import HttpResponse, Http404
from django.forms import modelform_factory, ModelForm, CharField, TextInput, ValidationError
from .models import Product
from django.utils.translation import gettext_lazy as _

# Create your views here.
def products(request):

	#the next variable typicaly is named 'queryset'
	list_products = Product.objects.order_by('-id')
	context = {
		#and the name on context usualy is "objct_list"
		'list_products': list_products,
		'meta_title': 'Productos',
		'meta_description': 'Lista de productos', 
	}
	return render(request, 'products/products.html', context)
	

	# response = ', '.join(['<br>Producto numero: {}, con nombre:  {}'.format(p.name, p.id) for p in list_products])
	# template = loader.get_template('products/products.html')
	# return HttpResponse(template.render(context, request))


def detail(request, id_product):
	# reponse = 'You are looking at product %s' % id_product
	# try:
	#	product = Product.objects.get(id=id_product)
	# except Product.DoesNotExist as e:
	#	raise Http404('Los detalles del producto no se encuentran... Lo borraste?')

	product = get_object_or_404(Product, id=id_product)
	context = {
		'product': product,
		'meta_title': product.name.title(),
		'meta_description': 'Muestra mas información acerca del producto {}'.format(product.name.title()),
	}
	return render(request, 'products/details.html', context)


# This handling post of form and rendering the form without ModelForm
"""
def form(request):

	if request.method == 'POST':
		name = request.POST.get('name')
		description = request.POST.get('description')

		try:

			Product.objects.create(name=name, description=description)
			msg = 'Guardado'
		except Exception as exception:
			print(exception.__class__.__name__)
			msg= 'Ya existe el producto \'{}\''.format(name)		

	else:
		msg = ''
		

	context = {
		'msg': msg
	}

	return render(request, 'products/form.html', context)
"""



# This's a example of ModelForm without factory 
class ProductForm(ModelForm):
	"""
	name = CharField(
		label="Nombre",
		widget= TextInput(
			attrs={
					'placeholder': 'Nombre de producto'
				}

			)

		)
	"""
	class Meta:
		model= Product
		fields= (
			'name',
			'description'
		)

		widgets= {
			'name': TextInput(
					attrs={
						'placeholder': _('Nombre del producto'),
						'class': 'form-input'
					}
				),
			'description': TextInput(
				attrs={
					'placeholder': _('Descripción del producto'),
					'class': 'form-input'
				}
			)
		}

		labels= {
			'name': _('Nombre'),
			'description': _('Descripción')
		}

	def clean_name(self, *args, **kwargs):
		#this methosd is to validate the product's name

		#get the data name after the default form validation
		name = self.cleaned_data.get('name')
		#then checks the lengths
		if len(name) > 20:
			#raise a error if is nor valid
			raise ValidationError('El nombre es muy largo')
			#return the name to continue further
		return name
"""
		widgets = {
            'name': CharField(attrs={'cols': 80, 'rows': 20}),
        }
"""
	


# This was a form rendered with modelform_factory
# Now use a created ModelForm
def form(request, id_product=False):



	#ProductForm = modelform_factory(Product, fields=('name', 'description'))
	
	if request.method == 'POST':
		form = ProductForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			print(form.cleaned_data)
		else:
			print(form.errors)
	#check if exist a product's id
	elif not id_product == False:
			#and then use it to get a product
			product = get_object_or_404(Product, id=id_product)
		
			#which is used to fill a Model Form with data
			form = ProductForm(request.POST or None, request.FILES or None , instance=product)
	else:
		form = ProductForm()

	context = {
		'form': form,
		'meta_title': _('Formulario De Productos'),
		'meta_description': _('Lugar para agregar o modificar productos'),
		'id_product': id_product,
	}

	return render(request, 'products/form.html', context)


def delete(request, id_product):
	
	if request.method == 'POST':
		product = get_object_or_404(Product, id=id_product)
		print(id_product)
		product.delete()
		return redirect("../")

	context = {

	}

	return render(request, "products/products.html", context)




#Used to render a form and use build-in django validation
"""
class RawForm(forms.Form):
	name= forms.CharField()
	description= form.CharField()
"""

supplies_request/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def supplies_request(request):
	return HttpResponse('Spl')

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title>{{ meta_title }} - Finanzas Locales</title>
	<meta rel="description" content="{{ meta_description }}">
	<meta rel="viewport" content="width=device-width initial-scale=1.0">
	<style type="text/css">
		.main-nav{
			padding: 0.4rem;
			margin-bottom: 1rem;
			border-bottom: 1px solid lightgray;
			box-shadow: 0px 3px 1px lightgray;
		}

		.main-footer{
			padding: 0.4rem;
			margin-bottom: 1rem;
			border-top: 1px solid lightgray;
			box-shadow: 0px -3px 1px lightgray;	
			background-color: lightskyblue;
			/*border-radius: 4px;*/
		}
	</style>
</head>
<body>
	<nav class="main-nav">
		<span>
			<a href="{% url 'products:products' %}">
				Productos
			</a>
		</span>
	</nav>
	{% block content%}

	{% endblock %}

	{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<footer class="main-footer">
	Hey! acabo de conocerte, y esto es loco, pero este es mi número. Asi que llamame, quizá (?)
</footer>

templates/products/details.html
{% extends 'base.html' %}

{% block content %}
	<ul>
		<li>
			Nombre: {{product.name.title}}
		</li>

		<li>
			Descripción: {{product.description}}
		</li>
	</ul>

{% endblock%}

templates/products/form.html
{% extends 'base.html' %}

{% block content %}
	<div>
		<form method="POST"> {% csrf_token %}

			{{form.as_p}}

		<!--	<div>
				<label for="name">
					Nombre:
				</label>
				<input type="text" name="name" id="name">
			</div>
			<div>
				<label for="description">
					Descripción:
				</label>
				<input type="text" name="description" id="description">
			</div>
		-->
			<button id="submit-add" type="submit">Guardar y añadir otro</button>
			<button id="submit-edit" type="submit">Guardar y continuar editando</button>
			<button id="submit" type="submit">Guardar</button>
			<div>
				{{msg}}
			</div>
			
		</form>

		<form id="delete_product" action="{{request.build_absolute_uri}}/eliminar" method="POST">
			{% csrf_token %}

			<button id="submit" type="submit">Eliminar</button>
		</form>
	</div>

{% endblock %}

templates/products/products.html
{% extends 'base.html' %}

{% block content %}
	<div>
		<button><a href="{% url 'products:product_form' %}">Agregar</a></button>
	</div>
	{% if list_products %}

		<ul>
			{% for product in list_products %}

				<li>
					<a href="{{product.get_absolute_url}}">{{product.name.title}}</a>
					
				</li>

			{% endfor %}
		</ul>

		{% else %}

		<p>Olvidaste añadir productos? Agrega unos.</p>

	{% endif %}
{% endblock %}